# Generated by Django 5.2.3 on 2025-06-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_etudiant', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('niveau', models.CharField(max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
