# Generated by Django 5.2.3 on 2025-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='classe',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
